// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@echome.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/sessions": {
            "get": {
                "description": "获取指定用户的所有会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "获取用户会话列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Session"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的用户会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "创建新会话",
                "parameters": [
                    {
                        "description": "会话创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "characterId": {
                                    "type": "string"
                                },
                                "userId": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}": {
            "get": {
                "description": "根据ID获取特定会话的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "获取会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/sessions/{id}/messages": {
            "get": {
                "description": "获取特定会话的所有消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "获取会话消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Message"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "向特定会话发送消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "消息内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "content": {
                                    "type": "string"
                                },
                                "sender": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Message"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/characters": {
            "get": {
                "description": "获取所有可用角色的列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "获取所有角色",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Character"
                            }
                        }
                    }
                }
            }
        },
        "/characters/search": {
            "get": {
                "description": "Search for roles by query string",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Search roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Character"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/characters/{id}": {
            "get": {
                "description": "Get detailed information about a specific character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Get character by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Character ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Character"
                        }
                    }
                }
            }
        },
        "/ws/asr": {
            "get": {
                "description": "建立语音识别的WebSocket连接，用于实时语音转文本",
                "tags": [
                    "websocket"
                ],
                "summary": "语音识别WebSocket连接",
                "parameters": [
                    {
                        "type": "string",
                        "default": "paraformer-realtime-v2",
                        "description": "ASR模型名称",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "pcm",
                        "description": "音频格式",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 16000,
                        "description": "采样率",
                        "name": "sample_rate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        },
        "/ws/tts": {
            "get": {
                "description": "建立文本转语音的WebSocket连接，用于实时文本转语音",
                "tags": [
                    "websocket"
                ],
                "summary": "文本转语音WebSocket连接",
                "parameters": [
                    {
                        "type": "string",
                        "default": "qwen-tts-realtime",
                        "description": "TTS模型名称",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "Cherry",
                        "description": "语音ID",
                        "name": "voice",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "pcm",
                        "description": "响应格式",
                        "name": "response_format",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 24000,
                        "description": "采样率",
                        "name": "sample_rate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "server_commit",
                        "description": "模式",
                        "name": "mode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        },
        "/ws/voice-conversation/{sessionId}/{characterId}": {
            "get": {
                "description": "建立语音对话的WebSocket连接，整合ASR、AI和TTS的完整流程",
                "tags": [
                    "websocket"
                ],
                "summary": "语音对话WebSocket连接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ws/webrtc/{sessionId}/{userId}": {
            "get": {
                "description": "建立WebRTC信令的WebSocket连接，用于点对点通信",
                "tags": [
                    "websocket"
                ],
                "summary": "WebRTC信令WebSocket连接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Character": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "persona": {
                    "type": "string"
                },
                "voice_config": {
                    "$ref": "#/definitions/domain.VoiceProfile"
                }
            }
        },
        "domain.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sender": {
                    "description": "'user' or 'character'",
                    "type": "string"
                },
                "sessionID": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "domain.Session": {
            "type": "object",
            "properties": {
                "characterID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastActivity": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.VoiceProfile": {
            "type": "object",
            "properties": {
                "custom_params": {
                    "description": "Custom parameters for TTS",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "language": {
                    "description": "Language code (zh-CN, en-US, etc.)",
                    "type": "string"
                },
                "pitch": {
                    "description": "Pitch adjustment (-500 to 500)",
                    "type": "number"
                },
                "speaking_style": {
                    "description": "Speaking style",
                    "type": "string"
                },
                "speech_rate": {
                    "description": "Speech rate (0.5-2.0)",
                    "type": "number"
                },
                "voice": {
                    "description": "Aliyun TTS voice ID",
                    "type": "string"
                },
                "volume": {
                    "description": "Volume (0.0-1.0)",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "EchoMe API",
	Description:      "This is a sample server for EchoMe application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
