basePath: /api
definitions:
  domain.Character:
    properties:
      avatar_url:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      persona:
        type: string
      voice_config:
        $ref: '#/definitions/domain.VoiceProfile'
    type: object
  domain.VoiceProfile:
    properties:
      custom_params:
        additionalProperties:
          type: string
        description: Custom parameters for TTS
        type: object
      language:
        description: Language code (zh-CN, en-US, etc.)
        type: string
      pitch:
        description: Pitch adjustment (-500 to 500)
        type: number
      speaking_style:
        description: Speaking style
        type: string
      speech_rate:
        description: Speech rate (0.5-2.0)
        type: number
      voice:
        description: Aliyun TTS voice ID
        type: string
      volume:
        description: Volume (0.0-1.0)
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@echome.com
    name: API Support
  description: This is a sample server for EchoMe application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EchoMe API
  version: "1.0"
paths:
  /characters:
    get:
      consumes:
      - application/json
      description: 获取所有可用角色的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Character'
            type: array
      summary: 获取所有角色
      tags:
      - characters
    post:
      consumes:
      - application/json
      description: 创建一个新角色
      parameters:
      - description: 角色信息
        in: body
        name: character
        required: true
        schema:
          $ref: '#/definitions/domain.Character'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Character'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 创建角色
      tags:
      - characters
  /characters/{id}:
    get:
      consumes:
      - application/json
      description: 根据角色ID获取详细信息
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Character'
      summary: 获取角色详情
      tags:
      - characters
  /ws/asr:
    get:
      description: 建立语音识别的WebSocket连接，用于实时语音转文本
      responses:
        "101":
          description: Switching Protocols
      summary: 语音识别WebSocket连接
      tags:
      - websocket
  /ws/tts:
    get:
      description: 建立文本转语音的WebSocket连接，用于实时文本转语音
      parameters:
      - description: 文本
        in: path
        name: text
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
      summary: 文本转语音WebSocket连接
      tags:
      - websocket
  /ws/voice-conversation:
    get:
      description: 建立WebSocket连接，用户通过WebSocket消息发送语音或文本，返回AI生成的响应
      parameters:
      - default: zh
        description: 语言
        in: query
        name: language
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 语音对话WebSocket连接
      tags:
      - websocket
  /ws/webrtc/{sessionId}/{userId}:
    get:
      description: 建立WebRTC信令的WebSocket连接，用于点对点通信
      parameters:
      - description: 会话ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: 用户ID
        in: path
        name: userId
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: WebRTC信令WebSocket连接
      tags:
      - websocket
swagger: "2.0"
