basePath: /api
definitions:
  domain.Character:
    properties:
      avatar_url:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      persona:
        type: string
      voice_config:
        $ref: '#/definitions/domain.VoiceProfile'
    type: object
  domain.Message:
    properties:
      content:
        type: string
      id:
        type: string
      sender:
        description: '''user'' or ''character'''
        type: string
      sessionID:
        type: string
      timestamp:
        type: string
    type: object
  domain.Session:
    properties:
      characterID:
        type: string
      createdAt:
        type: string
      id:
        type: string
      lastActivity:
        type: string
      userID:
        type: string
    type: object
  domain.VoiceProfile:
    properties:
      custom_params:
        additionalProperties:
          type: string
        description: Custom parameters for TTS
        type: object
      language:
        description: Language code (zh-CN, en-US, etc.)
        type: string
      pitch:
        description: Pitch adjustment (-500 to 500)
        type: number
      speaking_style:
        description: Speaking style
        type: string
      speech_rate:
        description: Speech rate (0.5-2.0)
        type: number
      voice:
        description: Aliyun TTS voice ID
        type: string
      volume:
        description: Volume (0.0-1.0)
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@echome.com
    name: API Support
  description: This is a sample server for EchoMe application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EchoMe API
  version: "1.0"
paths:
  /api/sessions:
    get:
      consumes:
      - application/json
      description: 获取指定用户的所有会话
      parameters:
      - description: 用户ID
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Session'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取用户会话列表
      tags:
      - sessions
    post:
      consumes:
      - application/json
      description: 创建一个新的用户会话
      parameters:
      - description: 会话创建请求
        in: body
        name: request
        required: true
        schema:
          properties:
            characterId:
              type: string
            userId:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Session'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 创建新会话
      tags:
      - sessions
  /api/sessions/{id}:
    get:
      consumes:
      - application/json
      description: 根据ID获取特定会话的详细信息
      parameters:
      - description: 会话ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Session'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取会话详情
      tags:
      - sessions
  /api/sessions/{id}/messages:
    get:
      consumes:
      - application/json
      description: 获取特定会话的所有消息
      parameters:
      - description: 会话ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取会话消息
      tags:
      - sessions
    post:
      consumes:
      - application/json
      description: 向特定会话发送消息
      parameters:
      - description: 会话ID
        in: path
        name: id
        required: true
        type: string
      - description: 消息内容
        in: body
        name: request
        required: true
        schema:
          properties:
            content:
              type: string
            sender:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Message'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 发送消息
      tags:
      - sessions
  /characters:
    get:
      consumes:
      - application/json
      description: 获取所有可用角色的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Character'
            type: array
      summary: 获取所有角色
      tags:
      - characters
  /characters/{id}:
    get:
      consumes:
      - application/json
      description: Get detailed information about a specific character
      parameters:
      - description: Character ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Character'
      summary: Get character by ID
      tags:
      - characters
  /characters/search:
    get:
      consumes:
      - application/json
      description: Search for roles by query string
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Character'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search roles
      tags:
      - characters
  /ws/asr:
    get:
      description: 建立语音识别的WebSocket连接，用于实时语音转文本
      parameters:
      - default: paraformer-realtime-v2
        description: ASR模型名称
        in: query
        name: model
        type: string
      - default: pcm
        description: 音频格式
        in: query
        name: format
        type: string
      - default: 16000
        description: 采样率
        in: query
        name: sample_rate
        type: integer
      responses:
        "101":
          description: Switching Protocols
      summary: 语音识别WebSocket连接
      tags:
      - websocket
  /ws/tts:
    get:
      description: 建立文本转语音的WebSocket连接，用于实时文本转语音
      parameters:
      - default: qwen-tts-realtime
        description: TTS模型名称
        in: query
        name: model
        type: string
      - default: Cherry
        description: 语音ID
        in: query
        name: voice
        type: string
      - default: pcm
        description: 响应格式
        in: query
        name: response_format
        type: string
      - default: 24000
        description: 采样率
        in: query
        name: sample_rate
        type: integer
      - default: server_commit
        description: 模式
        in: query
        name: mode
        type: string
      responses:
        "101":
          description: Switching Protocols
      summary: 文本转语音WebSocket连接
      tags:
      - websocket
  /ws/voice-conversation/{sessionId}/{characterId}:
    get:
      description: 建立语音对话的WebSocket连接，整合ASR、AI和TTS的完整流程
      parameters:
      - description: 会话ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: 角色ID
        in: path
        name: characterId
        required: true
        type: string
      - description: 用户ID
        in: query
        name: userId
        type: string
      - default: zh-CN
        description: 语言
        in: query
        name: language
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 语音对话WebSocket连接
      tags:
      - websocket
  /ws/webrtc/{sessionId}/{userId}:
    get:
      description: 建立WebRTC信令的WebSocket连接，用于点对点通信
      parameters:
      - description: 会话ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: 用户ID
        in: path
        name: userId
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: WebRTC信令WebSocket连接
      tags:
      - websocket
swagger: "2.0"
