basePath: /api
definitions:
  domain.Character:
    properties:
      avatar:
        description: 角色头像URL
        type: string
      created_at:
        type: string
      description:
        description: 角色描述
        type: string
      flag:
        description: 是否克隆音色
        type: boolean
      id:
        type: string
      name:
        description: 角色名
        type: string
      prompt:
        description: 角色提示词
        type: string
      status:
        description: '音色状态，使用枚举值: 1-审核中, 2-可用, 3-禁用'
        type: integer
      updated_at:
        type: string
      voice:
        description: 角色音色
        type: string
    type: object
  interfaces.CreateCharacterRequest:
    properties:
      audio:
        description: 可选，音频文件
        type: string
      avatar:
        description: 可选，角色头像
        type: string
      description:
        description: 可选，角色描述
        type: string
      flag:
        description: 必须，标志位
        type: boolean
      name:
        description: 必须，角色名称
        type: string
      prompt:
        description: 必须，角色提示词
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@echome.com
    name: API Support
  description: This is a sample server for EchoMe application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EchoMe API
  version: "1.0"
paths:
  /api/character:
    post:
      consumes:
      - application/json
      description: 通过语音克隆创建角色
      parameters:
      - description: 创建角色的请求体参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.CreateCharacterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 创建角色（语音克隆）
      tags:
      - characters
  /api/characters:
    get:
      consumes:
      - application/json
      description: 获取所有可用角色的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Character'
            type: array
      summary: 获取所有角色
      tags:
      - characters
  /api/characters/{id}:
    get:
      consumes:
      - application/json
      description: 根据角色ID获取详细信息
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Character'
      summary: 获取角色详情
      tags:
      - characters
  /ws/asr:
    get:
      description: 建立语音识别的WebSocket连接，用于实时语音转文本
      responses:
        "101":
          description: Switching Protocols
      summary: 语音识别WebSocket连接
      tags:
      - websocket
  /ws/voice-conversation:
    get:
      description: 建立WebSocket连接，用户通过WebSocket消息发送语音或文本，返回AI生成的响应
      parameters:
      - description: 角色ID
        in: query
        name: characterId
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 语音对话WebSocket连接
      tags:
      - websocket
  /ws/webrtc/{sessionId}/{userId}:
    get:
      description: 建立WebRTC信令的WebSocket连接，用于点对点通信
      parameters:
      - description: 会话ID
        in: path
        name: sessionId
        required: true
        type: string
      - description: 用户ID
        in: path
        name: userId
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: WebRTC信令WebSocket连接
      tags:
      - websocket
swagger: "2.0"
