services:
  echome-be:
    image: ghcr.io/${OWNER_LOWER:-corcton}/echome-be:latest
    container_name: echome-be
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./config:/app/config:ro
    networks:
      - echome-net

  echome-fe:
    build:
      context: ../echome-fe
      args:
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - OSS_REGION=${OSS_REGION}
        - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
        - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
        - OSS_BUCKET=${OSS_BUCKET}
    image: ghcr.io/${OWNER_LOWER:-corcton}/echome-fe:latest
    container_name: echome-fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - OSS_REGION=${OSS_REGION}
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - echome-be
    networks:
      - echome-net

networks:
  echome-net:
    driver: bridge
