package main

import (
	"flag"
	"log"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/justin/echome-be/docs"
)

var configPath = flag.String("f", "config/etc/config.yaml", "config file path")

// @title EchoMe API
// @version 1.0
// @description This is a sample server for EchoMe application.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@echome.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /api
func main() {
	flag.Parse()

	log.Printf("Starting EchoMe API server...")
	log.Printf("Using configuration file: %s", *configPath)

	// Initialize the application with all dependencies
	log.Println("Initializing application dependencies...")
	application, err := InitializeApplication(*configPath)
	if err != nil {
		log.Fatalf("Failed to initialize application: %v\n", err)
	}
	// Run the application
	if err := application.Run(); err != nil {
		log.Fatalf("Application error: %v\n", err)
	}
}
