package main

import (
	"flag"
	"go.uber.org/zap"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/justin/echome-be/docs"
	"github.com/justin/echome-be/config"
)

var configPath = flag.String("f", "config/etc/config.yaml", "config file path")

// @title EchoMe API
// @version 1.0
// @description This is a sample server for EchoMe application.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@echome.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /api
func main() {
	flag.Parse()

	// 初始化全局日志
	config.InitLogger()

	zap.L().Info("Starting EchoMe API server...")
	zap.L().Info("Using configuration file: %s", zap.String("configPath", *configPath))

	// Initialize the application with all dependencies
	zap.L().Info("Initializing application dependencies...")
	application, err := InitializeApplication(*configPath)
	if err != nil {
		zap.L().Fatal("Failed to initialize application", zap.Error(err))
	}
	// Run the application
	if err := application.Run(); err != nil {
		zap.L().Fatal("Application error", zap.Error(err))
	}
}
