name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'echome-be/**'
  workflow_dispatch:
    inputs:
      go_version:
        description: "Go version (default 1.24.x)"
        required: false
        default: "1.24.x"

concurrency:
  group: deploy-be
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version || '1.24.x' }}
          check-latest: true

      - name: Download Go deps
        working-directory: echome-be
        run: go mod download

      - name: Build backend
        working-directory: echome-be
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o echome-be ./cmd/api/main.go
          file echome-be || true

      - name: Package release
        run: |
          mkdir -p dist
          cp -r echome-be/config echome-be/docs dist/ || true
          mv echome-be/echome-be dist/
          tar -czf dist/be_release_${{ github.sha }}.tar.gz -C dist echome-be echome-be/config echome-be/docs 2>/dev/null || tar -czf dist/be_release_${{ github.sha }}.tar.gz -C dist .
          ls -lh dist

      - name: Copy artifacts (BE tar + deploy script)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          source: "dist/be_release_${{ github.sha }}.tar.gz,deploy/deploy_be.sh"
          target: "/tmp"

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script_stop: true
          script: |
            chmod +x /tmp/deploy_be.sh
            BE_DEPLOY_PATH="${BE_DEPLOY_PATH:-/opt/echome-be}" bash /tmp/deploy_be.sh /tmp/be_release_${{ github.sha }}.tar.gz ${{ github.sha }}
