name: Deploy to Heroku
on:
  push:
    branches: [main]
    paths:
      - 'echome-be/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "echome-be"
          heroku_email: "crt@corcton.com"
          appdir: "echome-be"